openapi: 3.0.3
info:
  version: 1.0.0
  title: Cloudeko API
  contact:
    name: Cloudeko
    url: https://www.cloudeko.dev
    email: support@cloudeko.dev
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.html
  description: >
    # Introduction
    
    Welcome to the Cloudeko API! You can use our API to access Cloudeko API endpoints.
externalDocs:
  description: Find out more about Cloudeko
  url: https://docs.cloudeko.dev
servers:
  - url: https://api.cloudeko.dev
    description: Production server
tags:
  - name: User
    description: Provides information about the user
  - name: Team
    description: >-
      Teams are groups of users who work together on projects. Teams can be used to
      manage access to resources and to organize users.
paths:
  /v1/user:
    $ref: './paths/user/user.yaml'
  /v1/teams:
    $ref: './paths/team/team.yaml'
  /v1/teams/{team}:
    $ref: './paths/team/team_{team}.yaml'
  /v1/teams/{team}/projects:
    $ref: './paths/team/team_{team}_projects.yaml'
  /v1/teams/{team}/roles:
    $ref: './paths/team/team_{team}_roles.yaml'
  /v1/teams/{team}/roles/{role}:
    $ref: './paths/team/team_{team}_roles_{role}.yaml'
  /v1/teams/{team}/members:
    $ref: './paths/team/team_{team}_members.yaml'
  /v1/teams/{team}/members/{user}:
    $ref: './paths/team/team_{team}_members_{user}.yaml'
  /v1/projects:
    $ref: './paths/project/project.yaml'
  /v1/projects/{project}:
    $ref: './paths/project/project_{project}.yaml'